Spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/DemoTestUnit
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create